theme: jekyll-theme-minimal
title: 'Temporal dynamics of microbial mats
        a network based approach'
author : ' Valerie De Anda'
logo: https://valdeanda.github.io/Time_series_mats/figures/b_oct13.jpg
show_downloads: true
