theme: jekyll-theme-minimal
title: [The title of your site]
description: [A short description of your site's purpose]
logo: [https://valdeanda.github.io/Time_series_mats/figures/b_oct13.jpg]
show_downloads: ["true" 
google_analytics: [Your Google Analytics tracking ID]
